package agentd

import (
	"encoding/json"
	"path/filepath"
	"strings"
	"testing"
)

// Every tool the agent gets resolves its path here, so a traversal that
// escapes the workspace has to fail in this one function or it fails nowhere.
func TestResolveConfinesToRoot(t *testing.T) {
	root := t.TempDir()
	escapes := []string{"../outside", "a/../../outside", "/etc/passwd", "sub/../../.."}
	for _, p := range escapes {
		if got, err := resolve(roots{workspace: root}, p); err == nil {
			t.Errorf("resolve(%q) = %q, want an out-of-workspace error", p, got)
		}
	}
}

// The ordinary cases must still work, including an absolute path that happens
// to be inside the workspace -- the model is told it may use either form.
func TestResolveAllowsInsideRoot(t *testing.T) {
	root := t.TempDir()
	inside := map[string]string{
		"go.mod":                    filepath.Join(root, "go.mod"),
		"./a/b.txt":                 filepath.Join(root, "a", "b.txt"),
		filepath.Join(root, "x.md"): filepath.Join(root, "x.md"),
	}
	for in, want := range inside {
		got, err := resolve(roots{workspace: root}, in)
		if err != nil {
			t.Fatalf("resolve(%q): %v", in, err)
		}
		if got != want {
			t.Errorf("resolve(%q) = %q, want %q", in, got, want)
		}
	}
}

// A prefix check alone would let a sibling directory through: /work-other
// starts with /work. The separator in the comparison is what stops it.
func TestResolveRejectsSiblingWithSharedPrefix(t *testing.T) {
	root := t.TempDir()
	if _, err := resolve(roots{workspace: root}, root+"-other/secret"); err == nil {
		t.Error("a sibling directory sharing the root's prefix was allowed in")
	}
}

// An oversized file must announce that it was cut. Silently truncating would
// let the model answer confidently about a file it only half saw.
func TestCapTextFlagsTruncation(t *testing.T) {
	got := capText(strings.Repeat("x", readCap+1))
	if !strings.Contains(got, "[truncated") {
		t.Error("a file over the cap was truncated with no notice")
	}
	if small := capText("short"); small != "short" {
		t.Errorf("capText altered a small file: %q", small)
	}
}

// The schema the model sees is generated by reflection over readInput, so a
// mistyped struct tag degrades it silently rather than failing the build.
//
// The comma is the trap: it separates jsonschema tag options, so a description
// containing one is truncated at the comma with no error. This test caught
// exactly that, and pins the description against regrowing a comma.
func TestReadSchemaSurvivesTagParsing(t *testing.T) {
	tools, err := Tools(roots{workspace: t.TempDir()}, NewGate(mustLog(t)), nil)
	if err != nil {
		t.Fatal(err)
	}
	schema := tools[0].InputSchema()
	buf, err := json.Marshal(schema)
	if err != nil {
		t.Fatal(err)
	}
	var got struct {
		Properties map[string]struct{ Description string } `json:"properties"`
		Required   []string                                `json:"required"`
	}
	if err := json.Unmarshal(buf, &got); err != nil {
		t.Fatal(err)
	}
	if len(got.Required) != 1 || got.Required[0] != "path" {
		t.Errorf("required = %v, want [path]", got.Required)
	}
	if d := got.Properties["path"].Description; !strings.Contains(d, "workspace") {
		t.Errorf("path description = %q, want the full sentence; a comma in the struct tag truncates it", d)
	}
}

// mustLog opens a throwaway log for tests that need a gate.
func mustLog(t *testing.T) *Log {
	t.Helper()
	l, err := OpenLog(t.TempDir(), "boss")
	if err != nil {
		t.Fatal(err)
	}
	return l
}
